name: My First Github Action
on: [push]
jobs: 
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
            - run: node -v
